//
//  DealItem.swift
//  stuk
//

import SwiftUI

struct DealItem: Identifiable, Hashable {
    let id = UUID()
    let brand: String
    let title: String
    let imageURL: String
    let accentColor: Color
    let buttonColor: Color
    let description: String
    let category: String
    let isCampaign: Bool
    let terms: String

    static func == (lhs: DealItem, rhs: DealItem) -> Bool { lhs.id == rhs.id }
    func hash(into hasher: inout Hasher) { hasher.combine(id) }
}

/// Build a stable Picsum URL from a brand seed.
private func pic(_ seed: String, _ w: Int = 600, _ h: Int = 800) -> String {
    "https://picsum.photos/seed/\(seed)/\(w)/\(h)"
}

enum DealStore {

    // MARK: Hot deals
    static let hotDeals: [DealItem] = [
        DealItem(brand: "Samsung", title: "50% studentrabatt",
                 imageURL: pic("samsung-tv-football"),
                 accentColor: Color(red: 0.05, green: 0.18, blue: 0.05),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Ladda upp inför sommarens Fotbolls-VM med upp till 50% på utvalda TV-modeller hos Samsung - Gör dig redo för en spännande sommar med fotboll i världsklass!",
                 category: "Datorer, Mjukvara & Teknik", isCampaign: true,
                 terms: "Erbjudandet gäller utvalda produkter under begränsad tid. Övriga frågor hänvisas till Samsungs kundtjänst."),
        DealItem(brand: "Viaplay", title: "Viaplay Total – 50% studentrabatt i 3 månader",
                 imageURL: pic("viaplay-sports-stars"),
                 accentColor: Color(red: 0.32, green: 0.05, blue: 0.10),
                 buttonColor: Color(red: 0.05, green: 0.78, blue: 0.45),
                 description: "Nu får du Viaplay Total till halva priset i 3 månader så du kan se Hockey-VM, Formel 1 samt den rafflande avslutningen på Premier League och finalerna av Svenska Cupen och Champions League!",
                 category: "TV & Streaming", isCampaign: true,
                 terms: "Erbjudandet gäller endast nya kunder. Bindningstid 3 månader."),
        DealItem(brand: "Lindex", title: "25% rabatt",
                 imageURL: pic("lindex-kids-pink"),
                 accentColor: Color(red: 0.55, green: 0.70, blue: 0.85),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Just nu får alla studenter 25% rabatt på hela sortimentet hos Lindex. Hitta din nya favoritplagg för säsongen.",
                 category: "Kläder & Mode", isCampaign: true,
                 terms: "Gäller ej redan rabatterade varor."),
        DealItem(brand: "Storytel", title: "Prova gratis 45 dagar + 50% studentrabatt",
                 imageURL: pic("storytel-headphones-flowers"),
                 accentColor: Color(red: 0.20, green: 0.35, blue: 0.40),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Få 45 dagars gratis Storytel och därefter 50% studentrabatt i 3 månader. Tusentals ljudböcker och e-böcker väntar.",
                 category: "TV & Streaming", isCampaign: true,
                 terms: "Endast nya kunder."),
        DealItem(brand: "Makeup Mekka", title: "Skönhet från 20 kr",
                 imageURL: pic("makeup-mekka-pink"),
                 accentColor: Color(red: 0.75, green: 0.55, blue: 0.75),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Stora rabatter på din favoritskönhet. Produkter från 20 kr just nu på Makeup Mekka.",
                 category: "Skönhet & Hudvård", isCampaign: true,
                 terms: "Så långt lagret räcker."),
        DealItem(brand: "Asus", title: "5% extra studentrabatt på rean",
                 imageURL: pic("asus-laptop"),
                 accentColor: Color.white,
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Få 5% extra studentrabatt ovanpå rean på ASUS laptops och tillbehör.",
                 category: "Datorer, Mjukvara & Teknik", isCampaign: true,
                 terms: "Kombineras inte med andra erbjudanden."),
        DealItem(brand: "STC", title: "1 månad extra träning + fri startavgift",
                 imageURL: pic("stc-running"),
                 accentColor: Color(red: 0.15, green: 0.18, blue: 0.20),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Få en månad gratis och slipp startavgiften när du tecknar studentmedlemskap på STC.",
                 category: "Sport & Träning", isCampaign: true,
                 terms: "12 månaders bindningstid."),
        DealItem(brand: "RVRC", title: "30-60% rabatt",
                 imageURL: pic("rvrc-mountain-sunset"),
                 accentColor: Color(red: 0.40, green: 0.30, blue: 0.20),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Outdoor-favoriter på rea. RVRC har 30-60% rabatt på utvalda produkter.",
                 category: "Sport & Träning", isCampaign: true,
                 terms: "Gäller utvalt sortiment."),
        DealItem(brand: "Sony", title: "20% rabatt på hörlurar",
                 imageURL: pic("sony-headphones"),
                 accentColor: Color(red: 0.20, green: 0.20, blue: 0.22),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Premium ljud till studentpris. 20% på Sony-hörlurar.",
                 category: "Datorer, Mjukvara & Teknik", isCampaign: true,
                 terms: "Gäller utvalda modeller."),
        DealItem(brand: "Samsung", title: "60% studentrabatt på Samsung Sound Tower",
                 imageURL: pic("samsung-sound-tower"),
                 accentColor: Color(red: 0.20, green: 0.16, blue: 0.20),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Festa till det med Samsung Sound Tower till 60% studentrabatt.",
                 category: "Datorer, Mjukvara & Teknik", isCampaign: true,
                 terms: "Gäller utvalda modeller."),
        DealItem(brand: "Telia", title: "AirPods på köpet",
                 imageURL: pic("telia-airpods"),
                 accentColor: Color(red: 0.16, green: 0.10, blue: 0.20),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Få AirPods på köpet när du tecknar abonnemang hos Telia.",
                 category: "Mobil & Bredband", isCampaign: true,
                 terms: "Bindningstid 24 månader."),
        DealItem(brand: "Telia", title: "Espressomaskin på köpet",
                 imageURL: pic("telia-espresso"),
                 accentColor: Color(red: 0.16, green: 0.10, blue: 0.20),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Espressomaskin följer med vid valda Telia-abonnemang.",
                 category: "Mobil & Bredband", isCampaign: true,
                 terms: "Bindningstid 24 månader."),
        DealItem(brand: "Sova", title: "20% studentrabatt",
                 imageURL: pic("sova-bedroom"),
                 accentColor: Color(red: 0.75, green: 0.78, blue: 0.82),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Sov bättre med 20% studentrabatt på sängar och tillbehör.",
                 category: "Inredning & Hushåll", isCampaign: true,
                 terms: "Gäller ordinarie pris."),
        DealItem(brand: "Outnorth", title: "25% rabatt på nästan allt",
                 imageURL: pic("outnorth-running"),
                 accentColor: Color(red: 0.60, green: 0.65, blue: 0.70),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Outnorth har 25% rabatt på nästan hela sortimentet.",
                 category: "Sport & Träning", isCampaign: true,
                 terms: "Gäller ej kampanjvaror."),
        DealItem(brand: "Hemtex", title: "Upp till 50% rabatt",
                 imageURL: pic("hemtex-bedroom"),
                 accentColor: Color(red: 0.30, green: 0.25, blue: 0.22),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Inred hemmet med Hemtex - just nu upp till 50% rabatt.",
                 category: "Inredning & Hushåll", isCampaign: true,
                 terms: "Gäller utvalda produkter."),
        DealItem(brand: "NordVPN", title: "Upp till 80% studentrabatt",
                 imageURL: pic("nordvpn-blue-portrait"),
                 accentColor: Color(red: 0.10, green: 0.20, blue: 0.50),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Säkra din internetuppkoppling med upp till 80% studentrabatt på NordVPN.",
                 category: "Datorer, Mjukvara & Teknik", isCampaign: true,
                 terms: "2-årigt abonnemang."),
        DealItem(brand: "Ur&Penn", title: "Deals från 20 kr",
                 imageURL: pic("urpenn-couple"),
                 accentColor: Color(red: 0.45, green: 0.40, blue: 0.38),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Smycken och accessoarer från 20 kr hos Ur&Penn.",
                 category: "Smycken & Accessoarer", isCampaign: true,
                 terms: "Så långt lagret räcker."),
        DealItem(brand: "Vue Nuex", title: "Upp till 70% rabatt",
                 imageURL: pic("vuenex-couple-pink"),
                 accentColor: Color(red: 0.85, green: 0.45, blue: 0.75),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Mode med kant - upp till 70% rabatt på Vue Nuex.",
                 category: "Kläder & Mode", isCampaign: true,
                 terms: "Endast online."),
        DealItem(brand: "Desenio", title: "Upp till 70% + 10% extra studentrabatt",
                 imageURL: pic("desenio-posters"),
                 accentColor: Color(red: 0.30, green: 0.35, blue: 0.25),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Posters för väggen - upp till 70% + 10% extra studentrabatt på Desenio.",
                 category: "Inredning & Hushåll", isCampaign: true,
                 terms: "Gäller utvalt sortiment."),
        DealItem(brand: "ICIW", title: "Upp till 70% + 10% extra studentrabatt",
                 imageURL: pic("iciw-active-pink"),
                 accentColor: Color(red: 0.50, green: 0.50, blue: 0.52),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Träna i stil. ICIW har upp till 70% rabatt + 10% extra för studenter.",
                 category: "Sport & Träning", isCampaign: true,
                 terms: "Gäller utvalda produkter."),
        DealItem(brand: "ASOS", title: "Upp till 70% rabatt",
                 imageURL: pic("asos-streetstyle"),
                 accentColor: Color(red: 0.40, green: 0.35, blue: 0.30),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "ASOS har just nu upp till 70% rabatt på säsongens hetaste plagg.",
                 category: "Kläder & Mode", isCampaign: true,
                 terms: "Gäller utvalt sortiment."),
        DealItem(brand: "Stutterheim", title: "Upp till 50% rabatt",
                 imageURL: pic("stutterheim-rain-jackets"),
                 accentColor: Color(red: 0.35, green: 0.38, blue: 0.40),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "På en, vad de minns som, grå och regnig dag i Stockholm 2010 föddes STUTTERHEIM ur ambitionen att inte bara hålla svenskarna torra – utan att kombinera modern skandinavisk design med europeiskt hantverk. Sedan dess har de utvecklats till ett svenskt livsstilsvarumärke som hämtar inspiration från Stockholms stadslandskap och håller stora delar av jordklotet torrt i alla väder. Trots att marknaden bara växer, designas och skapas varje produkt fortfarande i samma ateljé hemma i Stockholm, där de utvärderar, förfinar och designar om – för att behålla en estetik som har en stark modern identitet. Tillverkningen av alla produkter sker i Europa, för att hålla produktionen så lokal som möjligt, utan att kompromissa med kvaliteten.",
                 category: "Kläder & Mode", isCampaign: true,
                 terms: "Erbjudandet gäller utvalda produkter under begränsad tid. Övriga frågor hänvisas till Stutterheims kundtjänst."),
        DealItem(brand: "Comviq", title: "iPhone 17e från 339 kr/mån",
                 imageURL: pic("comviq-iphone17"),
                 accentColor: Color(red: 0.85, green: 0.85, blue: 0.85),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "iPhone 17e från 339 kr/månad med Comviqs studentabonnemang.",
                 category: "Mobil & Bredband", isCampaign: true,
                 terms: "24 månaders bindningstid."),
        DealItem(brand: "Nordic Nest", title: "Upp till 50% rabatt",
                 imageURL: pic("nordicnest-chair-interior"),
                 accentColor: Color(red: 0.35, green: 0.30, blue: 0.26),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Skandinavisk design med upp till 50% rabatt hos Nordic Nest.",
                 category: "Inredning & Hushåll", isCampaign: true,
                 terms: "Gäller utvalda produkter."),
        DealItem(brand: "Poster Store", title: "Upp till 70% + 10% extra studentrabatt",
                 imageURL: pic("posterstore-monet-bedroom"),
                 accentColor: Color(red: 0.55, green: 0.60, blue: 0.55),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Stora rabatter på posters hos Poster Store - upp till 70% + 10% extra.",
                 category: "Inredning & Hushåll", isCampaign: true,
                 terms: "Gäller utvalt sortiment."),
    ]

    // MARK: Populära rabatter
    static let popular: [DealItem] = [
        DealItem(brand: "hallon", title: "Från 19 kr/mån i 5 månader",
                 imageURL: pic("hallon-couple-smile"),
                 accentColor: Color(red: 0.80, green: 0.50, blue: 0.65),
                 buttonColor: Color(red: 0.95, green: 0.70, blue: 0.85),
                 description: "Från 19 kr/mån i 5 månader - inklusive 50 GB välkomstsurf! Hallon ger dig ett enkelt mobilabonnemang med skön frihet.",
                 category: "Mobil & Bredband", isCampaign: true,
                 terms: "Erbjudandet gäller endast nya kunder."),
        DealItem(brand: "ICIW", title: "20% studentrabatt",
                 imageURL: pic("iciw-women-sun"),
                 accentColor: Color(red: 0.55, green: 0.40, blue: 0.40),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "ICIW erbjuder 20% studentrabatt på hela sortimentet.",
                 category: "Sport & Träning", isCampaign: true,
                 terms: "Inkluderar inte redan nedsatta produkter."),
        DealItem(brand: "Daniel Wellington", title: "Upp till 25% + 20% studentrabatt",
                 imageURL: pic("daniel-wellington-watch"),
                 accentColor: Color(red: 0.30, green: 0.25, blue: 0.22),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Daniel Wellington kombinerar tidlös design med studentvänliga priser.",
                 category: "Smycken & Accessoarer", isCampaign: true,
                 terms: "Gäller utvalda klockor."),
        DealItem(brand: "Hudotek", title: "Spring box på köpet – Värde 2293 kr",
                 imageURL: pic("hudoteket-yellow"),
                 accentColor: Color(red: 0.95, green: 0.85, blue: 0.60),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Du får en exklusiv Spring Box på köpet vid abonnemang hos Hudoteket. Värde 2293 kr.",
                 category: "Skönhet & Hudvård", isCampaign: true,
                 terms: "Begränsat antal, så långt lagret räcker."),
        DealItem(brand: "Sony", title: "25% studentrabatt",
                 imageURL: pic("sony-streetstyle"),
                 accentColor: Color(red: 0.30, green: 0.30, blue: 0.32),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Få 25% studentrabatt på Sonys senaste hörlurar och högtalare.",
                 category: "Datorer, Mjukvara & Teknik", isCampaign: true,
                 terms: "Gäller endast online."),
    ]

    // MARK: Nya studentrabatter
    static let newDeals: [DealItem] = [
        DealItem(brand: "SF Anytime", title: "50% studentrabatt",
                 imageURL: pic("sfanytime-movies"),
                 accentColor: Color(red: 0.70, green: 0.20, blue: 0.20),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Halva priset på SF Anytime - filmer och serier till studentpris.",
                 category: "TV & Streaming", isCampaign: false,
                 terms: "Endast nya kunder."),
        DealItem(brand: "Suitable", title: "10% studentrabatt",
                 imageURL: pic("suitable-shirt"),
                 accentColor: Color(red: 0.35, green: 0.28, blue: 0.22),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Suitable erbjuder snygga skjortor och pikéer till studentpris.",
                 category: "Kläder & Mode", isCampaign: false,
                 terms: "Gäller hela sortimentet."),
        DealItem(brand: "Apple", title: "10% studentrabatt",
                 imageURL: pic("apple-airpods-mac"),
                 accentColor: Color(white: 0.10),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Apple ger 10% studentrabatt vid köp av Mac, iPad och tillbehör.",
                 category: "Datorer, Mjukvara & Teknik", isCampaign: false,
                 terms: "Vid uppvisande av Mecenat/STUK."),
        DealItem(brand: "H&M", title: "15% studentrabatt",
                 imageURL: pic("hm-store-front"),
                 accentColor: Color(white: 0.10),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Få 15% studentrabatt online och i butik hos H&M.",
                 category: "Kläder & Mode", isCampaign: false,
                 terms: "Gäller helt sortimentet."),
        DealItem(brand: "Rituals", title: "20% studentrabatt",
                 imageURL: pic("rituals-spa"),
                 accentColor: Color(white: 0.10),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Rituals 20% studentrabatt på alla produkter.",
                 category: "Skönhet & Hudvård", isCampaign: false,
                 terms: "Gäller online."),
    ]

    // MARK: TV & Streaming
    static let tvStreaming: [DealItem] = [
        DealItem(brand: "SF Anytime", title: "50% studentrabatt",
                 imageURL: pic("sfanytime-cards"),
                 accentColor: Color(red: 0.70, green: 0.20, blue: 0.20),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Halva priset på SF Anytime.", category: "TV & Streaming",
                 isCampaign: false, terms: "Endast nya kunder."),
        DealItem(brand: "TV4 Play Plus", title: "1 månad gratis",
                 imageURL: pic("tv4play-shows"),
                 accentColor: Color(red: 0.90, green: 0.10, blue: 0.10),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Få 1 månad gratis hos TV4 Play Plus.", category: "TV & Streaming",
                 isCampaign: false, terms: "Endast nya kunder."),
        DealItem(brand: "Viaplay", title: "50% i 3 månader",
                 imageURL: pic("viaplay-grid"),
                 accentColor: Color(red: 0.32, green: 0.05, blue: 0.10),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Viaplay Total till halva priset.", category: "TV & Streaming",
                 isCampaign: false, terms: "Endast nya kunder."),
    ]

    // MARK: Mobil & Bredband
    static let mobile: [DealItem] = [
        DealItem(brand: "Telia", title: "50 kr studentrabatt/mån",
                 imageURL: pic("telia-selfie-bridge"),
                 accentColor: Color(red: 0.16, green: 0.10, blue: 0.20),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Spara 50 kr/mån med Telias studentabonnemang.",
                 category: "Mobil & Bredband", isCampaign: false,
                 terms: "Bindningstid 24 månader."),
        DealItem(brand: "hallon", title: "Från 19 kr/mån i 5 månader",
                 imageURL: pic("hallon-couple-festival"),
                 accentColor: Color(red: 0.80, green: 0.50, blue: 0.65),
                 buttonColor: Color(red: 0.95, green: 0.70, blue: 0.85),
                 description: "hallon studentabonnemang från 19 kr/mån.",
                 category: "Mobil & Bredband", isCampaign: true,
                 terms: "Endast nya kunder."),
        DealItem(brand: "Comviq", title: "Månadens mobil från 499 kr/mån",
                 imageURL: pic("comviq-purple-phone"),
                 accentColor: Color(red: 0.25, green: 0.20, blue: 0.45),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Senaste smartphonen från Comviq.",
                 category: "Mobil & Bredband", isCampaign: true,
                 terms: "Bindningstid 24 månader."),
    ]

    // MARK: Kläder & Mode
    static let fashion: [DealItem] = [
        DealItem(brand: "Suitable", title: "10% studentrabatt",
                 imageURL: pic("suitable-portrait"),
                 accentColor: Color(red: 0.40, green: 0.30, blue: 0.22),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Suitable för studenter.", category: "Kläder & Mode",
                 isCampaign: false, terms: "Vid uppvisande av studentid."),
        DealItem(brand: "Weekday", title: "11% studentrabatt",
                 imageURL: pic("weekday-portrait"),
                 accentColor: Color(red: 0.55, green: 0.55, blue: 0.58),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Weekday ger 11% studentrabatt.", category: "Kläder & Mode",
                 isCampaign: false, terms: "Gäller online."),
        DealItem(brand: "Stutterheim", title: "Upp till 50% rabatt",
                 imageURL: pic("stutterheim-portrait-2"),
                 accentColor: Color(red: 0.35, green: 0.38, blue: 0.40),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Stutterheim Archive Sale.", category: "Kläder & Mode",
                 isCampaign: true, terms: "Begränsad tid."),
    ]

    // MARK: Hälsa & Apotek
    static let health: [DealItem] = [
        DealItem(brand: "MEDS", title: "20% studentrabatt",
                 imageURL: pic("meds-llama-products"),
                 accentColor: Color(red: 0.95, green: 0.70, blue: 0.78),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "MEDS – Ett riktigt bra apotek. 20% studentrabatt.",
                 category: "Hälsa & Apotek", isCampaign: false,
                 terms: "Gäller online."),
        DealItem(brand: "Apoteket", title: "15% studentrabatt",
                 imageURL: pic("apoteket-bottles-green"),
                 accentColor: Color(red: 0.15, green: 0.35, blue: 0.25),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Apoteket erbjuder 15% rabatt för studenter.",
                 category: "Hälsa & Apotek", isCampaign: false,
                 terms: "Gäller utvalda produkter."),
    ]

    // MARK: Sport & Träning
    static let sport: [DealItem] = [
        DealItem(brand: "ICIW", title: "20% studentrabatt",
                 imageURL: pic("iciw-pink-women"),
                 accentColor: Color(red: 0.55, green: 0.40, blue: 0.40),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "ICIW – träning i stil.", category: "Sport & Träning",
                 isCampaign: false, terms: "Gäller helt sortimentet."),
        DealItem(brand: "Fitness24Seven", title: "15% extra studentrabatt 3 månader",
                 imageURL: pic("fitness24seven-gym"),
                 accentColor: Color(red: 0.10, green: 0.22, blue: 0.40),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "15% extra studentrabatt på medlemskap i 3 månader.",
                 category: "Sport & Träning", isCampaign: false,
                 terms: "Bindningstid 12 månader."),
    ]

    // MARK: Smycken & Accessoarer
    static let jewelry: [DealItem] = [
        DealItem(brand: "Ur&Penn", title: "Deals från 20 kr",
                 imageURL: pic("urpenn-watches"),
                 accentColor: Color(red: 0.45, green: 0.40, blue: 0.38),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Smycken och accessoarer från 20 kr.",
                 category: "Smycken & Accessoarer", isCampaign: true,
                 terms: "Så långt lagret räcker."),
        DealItem(brand: "Daniel Wellington", title: "Upp till 25% + 20% studentrabatt",
                 imageURL: pic("dw-watches-table"),
                 accentColor: Color(red: 0.30, green: 0.25, blue: 0.22),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Tidlös design från Daniel Wellington.",
                 category: "Smycken & Accessoarer", isCampaign: true,
                 terms: "Gäller utvalda klockor."),
    ]

    // MARK: Misc categories (so sidemenu always has content)
    static let extras: [DealItem] = [
        DealItem(brand: "Adlibris", title: "Studentrabatt på kurslitteratur",
                 imageURL: pic("adlibris-books"),
                 accentColor: Color(red: 0.20, green: 0.30, blue: 0.50),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "10% studentrabatt på böcker och kurslitteratur hos Adlibris.",
                 category: "Böcker & Kurslitteratur", isCampaign: false,
                 terms: "Gäller utvalda titlar."),
        DealItem(brand: "Studentlitteratur", title: "15% studentrabatt",
                 imageURL: pic("studentlitteratur-shelf"),
                 accentColor: Color(red: 0.55, green: 0.30, blue: 0.20),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "15% studentrabatt på Studentlitteraturs kursböcker.",
                 category: "Böcker & Kurslitteratur", isCampaign: false,
                 terms: "Vid uppvisande av studentid."),
        DealItem(brand: "SJ", title: "Ungdomspris för dig under 26",
                 imageURL: pic("sj-train-platform"),
                 accentColor: Color(red: 0.30, green: 0.45, blue: 0.55),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Reser du med SJ? Ungdomspris för dig under 26 år.",
                 category: "Resor & Boende", isCampaign: false,
                 terms: "Vid uppvisande av legitimation."),
        DealItem(brand: "Scandic", title: "Studentpriser på hotell",
                 imageURL: pic("scandic-hotel-room"),
                 accentColor: Color(red: 0.20, green: 0.20, blue: 0.30),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Sov billigare hos Scandic med studentrabatt.",
                 category: "Resor & Boende", isCampaign: true,
                 terms: "Begränsat antal rum per natt."),
        DealItem(brand: "Mathem", title: "200 kr rabatt första leveransen",
                 imageURL: pic("mathem-groceries"),
                 accentColor: Color(red: 0.20, green: 0.35, blue: 0.20),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Studenter får 200 kr rabatt på första matkassen hos Mathem.",
                 category: "Matkassar & Livsmedel", isCampaign: true,
                 terms: "Endast nya kunder."),
        DealItem(brand: "HelloFresh", title: "Upp till 50% rabatt",
                 imageURL: pic("hellofresh-cook"),
                 accentColor: Color(red: 0.70, green: 0.40, blue: 0.20),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "HelloFresh studentkampanj - upp till 50% rabatt.",
                 category: "Matkassar & Livsmedel", isCampaign: true,
                 terms: "Endast nya kunder."),
        DealItem(brand: "SEB", title: "Studentkonto utan avgift",
                 imageURL: pic("seb-bank-card"),
                 accentColor: Color(red: 0.10, green: 0.30, blue: 0.50),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "SEBs studentkonto utan avgifter de första 5 åren.",
                 category: "Bank & Försäkring", isCampaign: false,
                 terms: "Gäller under studietiden."),
        DealItem(brand: "Folksam", title: "10% studentrabatt på försäkring",
                 imageURL: pic("folksam-protection"),
                 accentColor: Color(red: 0.45, green: 0.20, blue: 0.30),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Studenter får 10% rabatt på hemförsäkring hos Folksam.",
                 category: "Bank & Försäkring", isCampaign: false,
                 terms: "Gäller nya tecknade försäkringar."),
        DealItem(brand: "Interflora", title: "15% studentrabatt på blommor",
                 imageURL: pic("interflora-bouquet"),
                 accentColor: Color(red: 0.70, green: 0.35, blue: 0.45),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Skicka blommor med 15% studentrabatt hos Interflora.",
                 category: "Fest, Blommor & Nöje", isCampaign: false,
                 terms: "Gäller hela sortimentet."),
        DealItem(brand: "Systembolaget", title: "Fri leverans för studenter",
                 imageURL: pic("party-cheers-glasses"),
                 accentColor: Color(red: 0.50, green: 0.25, blue: 0.40),
                 buttonColor: Color(red: 0.92, green: 0.30, blue: 0.45),
                 description: "Festfixaren - fri leverans till nationen för studenter.",
                 category: "Fest, Blommor & Nöje", isCampaign: true,
                 terms: "20% självservicekrav."),
    ]

    /// Lookup table by category for HotDealsListView filtering.
    /// Falls back to a shuffled selection of all deals if no matches.
    static func byCategory(_ name: String?) -> [DealItem] {
        guard let name = name else { return hotDeals }
        let filtered = all.filter { $0.category == name }
        return filtered.isEmpty ? Array(all.shuffled().prefix(8)) : filtered
    }

    static var all: [DealItem] {
        hotDeals + popular + newDeals + tvStreaming + mobile + fashion + health + sport + jewelry + extras
    }

    /// Generates "Liknande rabatter" for a given deal — same category, excluding self.
    static func similar(to item: DealItem) -> [DealItem] {
        let sameCat = all.filter { $0.category == item.category && $0.id != item.id }
        return sameCat.isEmpty ? Array(all.shuffled().filter { $0.id != item.id }.prefix(4)) : sameCat
    }
}
